# Préparation des données

In [85]:
import numpy as np
file = open("ppPATCH.amat","r")
input = np.zeros((1,785))
j=0
for line in file:
    #j=j+1
    #if(j%1000==0):
    #    print(j)
    #if (j<5000 or j>= 45000):
    temp = line.strip().split(" ")
    for i in range(len(temp)):
        temp[i] = int(temp[i])
    temp = np.asarray(temp).reshape(1,785)
    input = np.append(input, temp, axis = 0)
print(input.shape)
print(input)

(50001, 785)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [86]:
# Enlève la première rangée
input1=np.delete(input, 0, 0)
# Mélange les données
np.random.shuffle(input1)
print(input1.shape)

(50000, 785)


In [87]:
from sklearn.svm import LinearSVC
x_train = input1[:40000, :784]
y_train = input1[:40000, 784]
x_test = input1[40000:, :784]
y_test = input1[40000:, 784]



# SVM linéaire

In [88]:
clf = LinearSVC(max_iter=100, random_state=0)
clf.fit(x_train, y_train)
print(clf.score(x_train, y_train))
print(clf.score(x_test, y_test))

0.52725
0.5115


# Réseau de neuronnes entièrement connecté

In [89]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(1000), random_state=1)
clf.fit(x_train, y_train)
print(clf.score(x_train, y_train))
print(clf.score(x_test, y_test))

0.966675
0.8522


# SVM linéaire

In [3]:
from sklearn.svm import LinearSVC
import warnings
warnings.filterwarnings('ignore')

def train_svm(c_values, folds=5):
    train_accuracies = []
    valid_accuracies = []
    
    for c_val in c_values:
        logs = []
        train_acc = []
        valid_acc = []
        
        for i in range(folds):
            cross_size = len(total_images) // folds
            split = cross_size * i

            train_x = np.concatenate([total_images[:split], total_images[split+cross_size:]])
            train_y = np.concatenate([total_labels[:split], total_labels[split+cross_size:]])

            valid_x = total_images[split:split+cross_size]
            valid_y = total_labels[split:split+cross_size]

            clf = LinearSVC(C=c_val, max_iter=100, random_state=0)
            
            clf.fit(train_x, train_y)
            train_acc.append(clf.score(train_x, train_y))
            valid_acc.append(clf.score(valid_x, valid_y))
            
        train_accuracies.append(np.mean(train_acc))
        valid_accuracies.append(np.mean(valid_acc))
        print('C:', c_val, 'Train Accuracy:', np.mean(train_acc), 'Valid Accuracy:', np.mean(valid_acc))
    
    return train_accuracies, valid_accuracies

In [4]:
train_accuracies, valid_accuracies = train_svm([100, 10, 1, 0.1, 0.01, 0.001, 0.0001])

C: 100 Train Accuracy: 0.7109 Valid Accuracy: 0.3049
C: 10 Train Accuracy: 0.6904999999999999 Valid Accuracy: 0.2968
C: 1 Train Accuracy: 0.7805500000000001 Valid Accuracy: 0.3396
C: 0.1 Train Accuracy: 0.7687 Valid Accuracy: 0.399
C: 0.01 Train Accuracy: 0.643575 Valid Accuracy: 0.4427
C: 0.001 Train Accuracy: 0.51915 Valid Accuracy: 0.4366
C: 0.0001 Train Accuracy: 0.394425 Valid Accuracy: 0.36549999999999994


In [5]:
train_accuracies, valid_accuracies = train_svm([0.012, 0.01, 0.008, 0.006, 0.004])

C: 0.012 Train Accuracy: 0.65475 Valid Accuracy: 0.4418
C: 0.01 Train Accuracy: 0.643575 Valid Accuracy: 0.4427
C: 0.008 Train Accuracy: 0.6300749999999999 Valid Accuracy: 0.4445
C: 0.006 Train Accuracy: 0.613275 Valid Accuracy: 0.4466
C: 0.004 Train Accuracy: 0.5913999999999999 Valid Accuracy: 0.4471


In [7]:
train_accuracies, valid_accuracies = train_svm([0.002, 0.001])

C: 0.002 Train Accuracy: 0.554125 Valid Accuracy: 0.4447
C: 0.001 Train Accuracy: 0.51915 Valid Accuracy: 0.4366


In [14]:
import sys
file = open("PATCH.amat","r")
i =0
j=0
for line in file:
    i = i+1
    for val in line:
        j = j+1
print(i)
print(j/i)

50000
12561.0


# Test

In [10]:
import numpy as np
file = open("ppPATCH.amat","r")
input = np.zeros((1,785))
i = 0
j=0
for line in file:
    j=j+1
    if(j%1000==0):
        print(j)
        break
    temp = line.strip().split(" ")
    for i in range(len(temp)):
        temp[i] = int(temp[i])
    temp = np.asarray(temp).reshape(1,785)
    input = np.append(input, temp, axis = 0)
print(input.shape)
print(input)

1000
(1000, 785)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 0. 0. 1.]]
